---
  - hosts: wgservers
    vars_files: 
      - group_vars/wgservers_vars.yml
    become: true
    remote_user: root
    tasks:
      - name: "Copy sshd_config"
        ansible.builtin.copy:
          src: files/sshd_config
          dest: /etc/ssh/sshd_config
          owner: root
          group: root
          mode: '0644'

      - name: "Restart sshd"
        service:
          name: sshd
          state: restarted
      
      - name: "Install wireguard"
        apt:
          name: wireguard
          state: present

      - debug: var=ansible_default_ipv4.address

      - name: "Allow ssh"
        ufw:
          rule: allow
          port: ssh
          proto: tcp

      - name: "Limit ssh connection rate"
        ufw:
          rule: limit
          port: ssh
          proto: tcp

      - name: "Enable ufw and set default policy to deny"
        ufw:
          state: enabled
          policy: deny

      - name: "Allow wireguard on port 41194"
        ufw:
          rule: allow
          proto: udp
          port: "{{ server_port }}"


      - name: "Put wireguard wg0 config"
        ansible.builtin.template:
          src: templates/wg0.conf.j2
          dest: /etc/wireguard/wg0.conf
          owner: root
          group: root
          mode: '0644'

      # TODO: parametrize interface
      - name: "Enable and start WireGuard service"
        service:
          name: "wg-quick@wg0"
          state: started
          enabled: true

      # TODO: autostart 
      # TODO: parametrize public keys thru key-value list in vars
